// Auto-generated by LibreLane
module ctrl(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input clk_i,
  input rst_in,
  input en_i,
  input we_i,
  input[1:0] adr_i,
  input[7:0] din_i,
  output[3:0] en_ros_o,
  output[2:0] en_load_o,
  output[5:0] sel_load_src_o,
  output[31:0] config_o
);
endmodule
