# SPDX-FileCopyrightText: 2026 The HeiChips Contributors
# SPDX-License-Identifier: Apache-2.0 WITH SHL-2.1
#
# LibreLane configuration file

meta:
  version: 3
  flow: Classic
  substituting_steps:

    # Magic reports some overlaps which can be ignored
    Checker.IllegalOverlap: null

DESIGN_NAME: heichips26_noise_gen
VERILOG_FILES: dir::../../rtl/*.sv
CLOCK_PORT: clk
CLOCK_NET: clk
CLOCK_PERIOD: 10 # 10ns = 100MHz

# SDC files
PNR_SDC_FILE: dir::impl.sdc
SIGNOFF_SDC_FILE: dir::signoff.sdc

# Reduce wasted space
TOP_MARGIN_MULT: 1
BOTTOM_MARGIN_MULT: 1
LEFT_MARGIN_MULT: 6
RIGHT_MARGIN_MULT: 6

# Absolute die size
FP_SIZING: absolute

# Tiny DEF template
#DIE_AREA: [0, 0, 200, 200]
#FP_DEF_TEMPLATE: dir::heichips26_template_tiny.def

# Small DEF template
DIE_AREA: [0, 0, 500, 200]
FP_DEF_TEMPLATE: dir::heichips26_template_small.def

# Large DEF template
#DIE_AREA: [0, 0, 500, 415]
#FP_DEF_TEMPLATE: dir::heichips26_template_large.def

# Don't use power rings or TopMetal1 layer
PDN_MULTILAYER: false
RT_MAX_LAYER: Metal4
PDN_VERTICAL_LAYER: Metal4
PDN_HORIZONTAL_LAYER: Metal3

# Enable for better SystemVerilog support
#USE_SLANG: true

MACROS:
  ctrl:
    gds:
      - dir::../../macros/ctrl/final/gds/ctrl.gds
    lef:
      - dir::../../macros/ctrl/final/lef/ctrl.lef
    vh:
      - dir::../../macros/ctrl/final/vh/ctrl.vh
    lib:
      nom_typ_1p20V_25C:
        - dir::../../macros/ctrl/final/lib/nom_typ_1p20V_25C/ctrl__nom_typ_1p20V_25C.lib
      nom_fast_1p32V_m40C:
        - dir::../../macros/ctrl/final/lib/nom_fast_1p32V_m40C/ctrl__nom_fast_1p32V_m40C.lib
      nom_slow_1p08V_125C:
        - dir::../../macros/ctrl/final/lib/nom_slow_1p08V_125C/ctrl__nom_slow_1p08V_125C.lib
    spef:
      nom:
        - dir::../../macros/ctrl/final/spef/nom/ctrl.nom.spef
    instances:
      i_noise_gen_top.i_ctrl:
        location: [30, 30]
        orientation: N

  a_ro:
    gds:
      - dir::../../macros/a_ro/final/gds/a_ro.gds
    lef:
      - dir::../../macros/a_ro/final/lef/a_ro.lef
    vh:
      - dir::../../macros/a_ro/final/vh/a_ro.vh
    lib:
      nom_typ_1p20V_25C:
        - dir::../../macros/a_ro/final/lib/nom_typ_1p20V_25C/a_ro__nom_typ_1p20V_25C.lib
      nom_fast_1p32V_m40C:
        - dir::../../macros/a_ro/final/lib/nom_fast_1p32V_m40C/a_ro__nom_fast_1p32V_m40C.lib
      nom_slow_1p08V_125C:
        - dir::../../macros/a_ro/final/lib/nom_slow_1p08V_125C/a_ro__nom_slow_1p08V_125C.lib
    spef:
      nom:
        - dir::../../macros/a_ro/final/spef/nom/a_ro.nom.spef
    instances:
      i_noise_gen_top.i_a_ro:
        location: [200, 140]
        orientation: N

  # b_ro:
  #   gds:
  #     - dir::../../macros/b_ro/final/gds/b_ro.gds
  #   lef:
  #     - dir::../../macros/b_ro/final/lef/b_ro.lef
  #   vh:
  #     - dir::../../macros/b_ro/final/vh/b_ro.vh
  #   lib:
  #     nom_typ_1p20V_25C:
  #       - dir::../../macros/b_ro/final/lib/nom_typ_1p20V_25C/b_ro__nom_typ_1p20V_25C.lib
  #     nom_fast_1p32V_m40C:
  #       - dir::../../macros/b_ro/final/lib/nom_fast_1p32V_m40C/b_ro__nom_fast_1p32V_m40C.lib
  #     nom_slow_1p08V_125C:
  #       - dir::../../macros/b_ro/final/lib/nom_slow_1p08V_125C/b_ro__nom_slow_1p08V_125C.lib
  #   spef:
  #     nom:
  #       - dir::../../macros/b_ro/final/spef/nom/b_ro.nom.spef
  #   instances:
  #     i_noise_gen_top.i_b_ro:
  #       location: [250, 140]
  #       orientation: N

  c_ro:
    gds:
      - dir::../../macros/c_ro/final/gds/c_ro.gds
    lef:
      - dir::../../macros/c_ro/final/lef/c_ro.lef
    vh:
      - dir::../../macros/c_ro/final/vh/c_ro.vh
    lib:
      nom_typ_1p20V_25C:
        - dir::../../macros/c_ro/final/lib/nom_typ_1p20V_25C/c_ro__nom_typ_1p20V_25C.lib
      nom_fast_1p32V_m40C:
        - dir::../../macros/c_ro/final/lib/nom_fast_1p32V_m40C/c_ro__nom_fast_1p32V_m40C.lib
      nom_slow_1p08V_125C:
        - dir::../../macros/c_ro/final/lib/nom_slow_1p08V_125C/c_ro__nom_slow_1p08V_125C.lib
    spef:
      nom:
        - dir::../../macros/c_ro/final/spef/nom/c_ro.nom.spef
    instances:
      i_noise_gen_top.i_c_ro:
        location: [190, 100]
        orientation: N

  d_ro_tapped:
    gds:
      - dir::../../macros/d_ro_tapped/final/gds/d_ro_tapped.gds
    lef:
      - dir::../../macros/d_ro_tapped/final/lef/d_ro_tapped.lef
    vh:
      - dir::../../macros/d_ro_tapped/final/vh/d_ro_tapped.vh
    lib:
      nom_typ_1p20V_25C:
        - dir::../../macros/d_ro_tapped/final/lib/nom_typ_1p20V_25C/d_ro_tapped__nom_typ_1p20V_25C.lib
      nom_fast_1p32V_m40C:
        - dir::../../macros/d_ro_tapped/final/lib/nom_fast_1p32V_m40C/d_ro_tapped__nom_fast_1p32V_m40C.lib
      nom_slow_1p08V_125C:
        - dir::../../macros/d_ro_tapped/final/lib/nom_slow_1p08V_125C/d_ro_tapped__nom_slow_1p08V_125C.lib
    spef:
      nom:
        - dir::../../macros/d_ro_tapped/final/spef/nom/d_ro_tapped.nom.spef
    instances:
      i_noise_gen_top.i_d_ro_tapped:
        location: [190, 30]
        orientation: N

  e_load_uniform:
    gds:
      - dir::../../macros/e_load_uniform/final/gds/e_load_uniform.gds
    lef:
      - dir::../../macros/e_load_uniform/final/lef/e_load_uniform.lef
    vh:
      - dir::../../macros/e_load_uniform/final/vh/e_load_uniform.vh
    lib:
      nom_typ_1p20V_25C:
        - dir::../../macros/e_load_uniform/final/lib/nom_typ_1p20V_25C/e_load_uniform__nom_typ_1p20V_25C.lib
      nom_fast_1p32V_m40C:
        - dir::../../macros/e_load_uniform/final/lib/nom_fast_1p32V_m40C/e_load_uniform__nom_fast_1p32V_m40C.lib
      nom_slow_1p08V_125C:
        - dir::../../macros/e_load_uniform/final/lib/nom_slow_1p08V_125C/e_load_uniform__nom_slow_1p08V_125C.lib
    spef:
      nom:
        - dir::../../macros/e_load_uniform/final/spef/nom/e_load_uniform.nom.spef
    instances:
      i_noise_gen_top.i_e_load_uniform:
        location: [340, 120]
        orientation: N

  f_load_binary:
    gds:
      - dir::../../macros/f_load_binary/final/gds/f_load_binary.gds
    lef:
      - dir::../../macros/f_load_binary/final/lef/f_load_binary.lef
    vh:
      - dir::../../macros/f_load_binary/final/vh/f_load_binary.vh
    lib:
      nom_typ_1p20V_25C:
        - dir::../../macros/f_load_binary/final/lib/nom_typ_1p20V_25C/f_load_binary__nom_typ_1p20V_25C.lib
      nom_fast_1p32V_m40C:
        - dir::../../macros/f_load_binary/final/lib/nom_fast_1p32V_m40C/f_load_binary__nom_fast_1p32V_m40C.lib
      nom_slow_1p08V_125C:
        - dir::../../macros/f_load_binary/final/lib/nom_slow_1p08V_125C/f_load_binary__nom_slow_1p08V_125C.lib
    spef:
      nom:
        - dir::../../macros/f_load_binary/final/spef/nom/f_load_binary.nom.spef
    instances:
      i_noise_gen_top.i_f_load_binary:
        location: [340, 60]
        orientation: N

  g_glitch:
    gds:
      - dir::../../macros/g_glitch/final/gds/g_glitch.gds
    lef:
      - dir::../../macros/g_glitch/final/lef/g_glitch.lef
    vh:
      - dir::../../macros/g_glitch/final/vh/g_glitch.vh
    lib:
      nom_typ_1p20V_25C:
        - dir::../../macros/g_glitch/final/lib/nom_typ_1p20V_25C/g_glitch__nom_typ_1p20V_25C.lib
      nom_fast_1p32V_m40C:
        - dir::../../macros/g_glitch/final/lib/nom_fast_1p32V_m40C/g_glitch__nom_fast_1p32V_m40C.lib
      nom_slow_1p08V_125C:
        - dir::../../macros/g_glitch/final/lib/nom_slow_1p08V_125C/g_glitch__nom_slow_1p08V_125C.lib
    spef:
      nom:
        - dir::../../macros/g_glitch/final/spef/nom/g_glitch.nom.spef
    instances:
      i_noise_gen_top.i_g_glitch:
        location: [340, 25]
        orientation: N